spring:
  application:
    name: EventIA

  datasource:
    url: jdbc:mysql://localhost:3306/eventia_db?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: eventia.gha@gmail.com
    password: "dgxl lvta lbkc noji"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
      debug: true

jwt:
  secret: UneCleSecreteTresLonguePourHS2561234567890
  expiration: 18000000 # 5 heures en millisecondes

server:
  port: 8081